Update apiTesting.yml

diff --git a/.github/workflows/apiTesting.yml b/.github/workflows/apiTesting.yml
--- a/.github/workflows/apiTesting.yml
+++ b/.github/workflows/apiTesting.yml
@@ -34,6 +34,11 @@ jobs:
           ref: gh-pages
           path: gh-pages
 
+      - name: Find allure-results field 
+        run: |
+          echo "Searching for allure-results directory..."
+          find / -type d -name "allure-results" 2>/dev/null || echo "Directory not found"
+          
       - name: Build Allure test report
         uses: simple-elf/allure-report-action@v1.7
         if: always()
