Update apiTesting.yml

diff --git a/.github/workflows/apiTesting.yml b/.github/workflows/apiTesting.yml
--- a/.github/workflows/apiTesting.yml
+++ b/.github/workflows/apiTesting.yml
@@ -19,6 +19,8 @@ jobs:
       - name: Run tests
         run: dotnet test ApiTestingSolution/ApiTestingSolution.sln --logger:"trx;LogFileName=test-results.trx"
         continue-on-error: true
+      - name: Set test result output
+        run: if [ $? -ne 0 ]; then echo "tests_failed=true" >> $GITHUB_ENV; else echo "tests_failed=false" >> $GITHUB_ENV; fi
       - name: Install Allure
         run: npm install -g allure-commandline --save-dev
       - name: Generate Allure report
